language: python
sudo: false

python:
  - pypy
  - pypy3
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - TZ=UTC
  matrix:
    - PYTHONOPTIMIZE=
    - PYTHONOPTIMIZE=1

install:
  - travis_retry pip install --upgrade setuptools pip pytest
  - travis_retry pip install tox tox-travis
  - travis_retry tox --notest -r

script: tox

notifications:
  irc:
    channels:
      - 'irc.freenode.org#webcore'
    use_notice: true
    skip_join: true

after_success:
  - coveralls
